### ISSUE TITLE
Skip outro missing notes

### ISSUE THREAD

**Issue by tchesket** [Kylemc1413/Intro-Skip#4]
In songs where it's possible to skip the outro, I've noticed several times that the last note or two of the song will get missed if I'm holding down the trigger already, I think it is skipping the final notes and needs to wait a little longer before skipping

**Comment by Kylemc1413** [comment]
Do you mean like if you're holding the trigger while the last note becomes level with you?

**Comment by tchesket** [comment]
Yes. Which I usually am, because of how I hold the controller. I imagine a
lot of other people do the same thing. Also I wouldn't say "level with me", I try to hit the notes like usual but it never seems to give me enough time to make them register, I'm pretty sure I am hitting them before they get to that point.

**Comment by Kylemc1413** [comment]
I might make outro skip look for longer outros (7+ seconds as an example) and then wait for a second after the last note to allow skipping then

**Comment by Kylemc1413** [comment]
It never allows you to skip when the last note is still way in the distance or anything, right?

**Comment by tchesket** [comment]
What happens is I go to swing at the last note, and even though it looks like the tip of my sword hits the note, as soon as that happens it skips ahead and it doesn't register as a hit. So like the instant I hit the last note it skips, but it doesn't take, it that makes sense.

**Comment by Kylemc1413** [comment]
Yeah that makes sense, I probably only need to add like half of a second after the last note before it lets you skip outros

**Comment by Kylemc1413** [comment]
Try version 3.0.1 and see if that resolves the issue

**Comment by tchesket** [comment]
Seems to be fixed now, haven't noticed it happen since updating. Thanks
