### ISSUE TITLE
1.18.3 broke it

### ISSUE THREAD

**Issue by DiSaber** [Kylemc1413/Intro-Skip#7]
@Kylemc1413 I'm actually surprised it lasted this long without an update but it would be helpful for me and a bunch of other people if you updated it (Or scrap all the code and remake it because it's so old).

**Comment by Kylemc1413** [comment]
The last release of intro skip (3.1.4) is still working on the latest version to my knowledge as nothing in 1.18.3 would have affected it

**Comment by DiSaber** [comment]
Oh my god I just realized that the version on beatmods.com is actually more recent than the one here. I just moved to a new pc and grabbed this one instead of just copying it from my old pc. Yep 3.1.4 from beatmods.com works, sorry about that :)
